[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'miyakogi/seiya.vim'

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
depends = ['plenary.nvim']

[[plugins]]
repo = 'nvim-telescope/telescope-fzf-native.nvim'
depends = ['telescope.nvim']
build = 'make'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
nmap <C-n> :NERDTreeToggle<CR>
let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'honza/vim-snippets'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'neoclide/coc.nvim'
rev = 'release'
merged = '0'
hook_add = '''
function! s:check_back_space() abort
  let col = col('.') - 1
  return !col || getline('.')[col - 1]  =~# '\s'
endfunction

noremap <C-f> :call CocAction('format')<CR>
inoremap <expr><cr> pumvisible() ? "\<C-y>" : "\<C-g>u\<CR>"

inoremap <silent><expr> <TAB>
  \ pumvisible() ? "\<C-n>" :
  \ <SID>check_back_space() ? "\<TAB>" :
  \ coc#refresh()
inoremap <expr><S-TAB> pumvisible() ? "\<C-p>" : "\<C-h>"
'''

[[plugins]]
repo = 'neoclide/coc-snippets'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-pairs'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-yank'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-tsserver'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-eslint'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-vetur'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-prettier'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-html'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-css'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-stylelint'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-json'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-yaml'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-solargraph'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-python'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'neoclide/coc-java'
build = 'yarn install > /dev/null'

[[plugins]]
repo = 'josa42/coc-go'
build = 'yarn install > /dev/null'
